language: python
matrix:
  include:
    - os: linux
      arch: arm64
      dist: bionic
      python: nightly
    - os: linux
      arch: amd64
      dist: bionic
      python: nightly
    - os: linux
      arch: arm64
      dist: xenial
      python: 3.6
    - os: linux
      arch: amd64
      dist: xenial
      python: 3.6
    - os: linux
      arch: arm64
      dist: xenial
      python: 3.5
    - os: linux
      arch: amd64
      dist: xenial
      python: 3.5
    - os: linux
      arch: arm64
      dist: xenial
      python: 3.4
    - os: linux
      arch: amd64
      dist: xenial
      python: 3.4
    - os: linux
      arch: arm64
      dist: xenial
      python: 2.7
    - os: linux
      arch: amd64
      dist: xenial
      python: 2.7
  allow_failures:
    - python: "nightly"
sudo: false
env:
install:
    - pip install --upgrade pytest
    - pip install . codecov
    - pip install nbformat[test]
script:
    - py.test -v --cov nbformat nbformat
after_success:
    - codecov
  
