language: python
python:
    - 3.6
    - 3.5
    - 3.4
    - 2.7
sudo: false
matrix:
  include:
    - os: linux
      arch: arm64
      dist: bionic
      python: nightly
    - os: linux
      arch: amd64
      dist: bionic
      python: nightly
os: linux
arch: 
    - amd64
    - arm64
env:
install:
    - pip install --upgrade pytest
    - pip install . codecov
    - pip install nbformat[test]
script:
    - py.test -v --cov nbformat nbformat
after_success:
    - codecov
matrix:
  allow_failures:
    - python: "nightly"

